---
title:
geometry: left=2cm, right=2cm, top=2cm, bottom=3cm, footskip = .5cm
output: 
  pdf_document:
    includes:
      in_header: latex/header.tex
    keep_tex: yes
bibliography: SOE2020.bib
csl: plos.csl
link-citations: yes
fontsize: 10pt
subparagraph: yes
---

```{r setup, include=FALSE}
#Default Rmd options
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center') #allows for inserting R code into captions

library(tidyverse)
library(readxl)
library(kableExtra)

```

# Introduction

In the table below we summarize all comments and requests with sources. The Progress column briefly summarizes how we responded, with a more detailed response in the numbered Memo Section. In the Progress column, "SOE" indicates a change included in the report(s).

```{r summtable}
# take from google drive to automatically update any changes
#googledrive::drive_download("Northeast IEA/State of the Ecosystem Reports/SOE 2020/Workshop & Meeting Notes/Request checklist", path="2019requests.xlsx", overwrite = TRUE)

knitr::kable(read_excel("2019requests.xlsx", sheet="MemoTable", range = 'A1:D32')) %>%
  kable_styling(latex_options = c("hold_position", "scale_down"))
```


# Responses to comments