---
author:
- Sarah Gaichas, PhD
- Research Fishery Biologist
- Ecosystem Dynamics and Assessment Branch
- Northeast Fisheries Science Center
opening: To the SSC,
closing: Sincerely,
date: "`r format(Sys.time(), '%d %B, %Y')`"
address:
- Mid-Atlantic Fishery Management Council
- 800 North State Street, Suite 201 
- Dover, DE 19901
encl:
 - "State of the Ecosystem 2025: Request Tracking Memo"
 - "Proxies for profit in the Mid-Atlantic"
cc:
- Jon Hare
letterhead: letterhead/NEFSCletterhead.pdf
signature: signature/gaichas.pdf
signature-before: -8ex

output: linl::linl

---

In this memo we list comments and requests received on the 2019-2024 State of the Ecosystem (SOE) reports, and how we responded to those requests. We include comments from both Councils because adjustments to the report were made in response to both. We welcome feedback on whether this memo is useful and how to improve it for future SOE reporting.

The attached document includes a table where we summarize all comments and requests with sources. Since 2023, the memo is organized into categories of requests in descending order of overall Council priority. The Rank column summarizes priority and was derived from combined discussion with the Mid-Atlantic SSC ecosystem working group and a survey of selected MAFMC members coordinated by Council staff in July 2022. Ranks were reviewed and updated by MAFMC and NEFMC SSC members in July 2024.

We specifically request feedback on the following topics to improve the utility of the SOE for the Council:

1.  Ecosystem level management objectives: is the list complete? Does the Council have reference points, desired states, or other performance metrics we should address for each objective?
1.  Current objective sections
    *  Profits objective and appropriate indicators: attached analysis with decision points
    *  Stability objective: are current indicators addressing Council needs?
1.  Forecasts: what decisions or contexts would ocean forecasts be most useful for? What are desired characteristics of a forecast?

We welcome comments on the entire SOE report as well as information included in this memo, and look forward to feedback from the SSC and Council.
