---
fontsize: 11pt
geometry: left=2cm, right=2cm, top=2cm, bottom=3cm, footskip = .5cm
link-citations: yes
output:
  pdf_document:
    includes:
      in_header: latex/header-sept22.tex
    keep_tex: yes
  html_document:
    df_print: paged
subparagraph: yes
urlcolor: blue
---

## Review of Objectives and Intended Outcomes

The MAFMC SSC Ecosystem Working Group (WG) was established in May 2021 to assist the Council in developing short term and long term objectives to advance the operational use of ecosystem information in management decisions. As reported in [September 2021](https://www.mafmc.org/s/b_Ecosystem-WG_Proposed-Tasks-August-2021.pdf), and in [March 2022](https://www.mafmc.org/s/d_March2022_SSCEcoWG.pdf) the WG has identified three general objectives:

1.  Expanding and clarifying the ecosystem portion of the SSC OFL CV determination process (short term objective)
2.  Developing prototype processes to provide multispecies and system level scientific advice appropriate for Council decision making, in particular where there are multispecies and multifleet tradeoffs linking directly to economic and social outcomes (long term objective)
3.  Collaborating with SSC species leads, stock assessment leads, and relevant working groups in developing the stock-specific Ecosystem and Socio-economic Profiles (ESP) process to specify stock-specific Ecosystem ToRs that are impactful and can be integrated into assessments (moderate-term objective)

Objectives 1 and 3 aim to integrate appropriate ecosystem information at the stock level of management decision making, while objective 2 applies to current Council EAFM processes and potential future multispecies and system level objectives.

Intended outcomes of WG work for the Council include:

-   An OFL CV process that makes better use of ecosystem information in determining the ABC
-   Evaluation of multiple ecosystem indicators and potential development of thresholds for use in a revised EAFM risk assessment and/or other Council processes
-   Increased range of opportunities for relevant ecosystem information to be considered in management decision processes

## Progress

Since March 2022 the WG has met twice (28 April, 18 July) and is scheduled to meet 30 September 2022.

In April, the WG outlined simulation work addressing Objective 1 and reviewed current ecosystem overfishing indicators addressing Objective 2. See details for both below.

In July, the WG reviewed a method addressing Objective 2 presented by John Walden (NEFSC). See details below. The WG also prioritized the request list for current and proposed ecosystem indicators to be worked on by the State of the Ecosystem (SOE) production team. This prioritization was used, along with priorities identified by selected MAFMC members, to outline work for the 2023 SOE reports at the August 2022 planning meeting.

In addition, WG member Sarah Gaichas participated in the SCS7 meeting in August 2022 and gave an overview of Ecosystem WG objectives and progress, as well as current MAFMC EAFM efforts. The combined MAFMC approaches were represented in [Keynote #2, Using Ecosystem Information in the Stock Assessment and Advice Process](https://noaa-edab.github.io/presentations/20220815_SCS7_Keynote2_Gaichas.html#1).

[SCS7 meeting materials](https://meetings.npfmc.org/Meeting/PrintableAgenda/2945?includeAttachments=True) include many case studies for integrating ecosystem information into assessments and management from around the US.

### Objective 1: OFL CV and ecosystem effects

WG member Mike Wilberg's lab (U. Maryland) is collaborating with John Wiedenmann's lab (Rutgers) to simulate an environmental effect on stock recruitment and test how it impacts assessment uncertainty. Implications of choosing both the appropriate OFL CV based on an environmental effect linked to recruitment and an inappropriate OFL CV will be evaluated using an updated MSE framework. The group is conducting a mini-review on environmental drivers in the region to get an idea of trends, periodicity, autocorrelation to inform the analysis. A simulated species based on Summer flounder is the initial case study, with extension to a simulated species based on Atlantic Mackerel proposed for future work. Work began in February 2022 with the students by introducing the project, what the overall goals were, and an introduction to the MSE code previously used in other MAFMC analyses. The MSE model has been updated with recent stock assessment information for summer flounder. The WG discussed options for scenarios to run, and types of climate forcing to use. The students will be invited to present to the WG and join discussions at the scheduled September working group meeting and as the project progresses.

### Objective 2: Multispecies and system level ecosystem advice

#### Ecosystem overfishing indicators

Andy Beet (NEFSC) and Sarah Gaichas presented detailed information on current [ecosystem overfishing (EOF) indicators](https://noaa-edab.github.io/presentations/20220428_SSCEcoWG_Gaichas.html#1) at the April meeting. These indicators were presented in the 2021 SOE. Work is in progress to improve the current indicators, including updating landings estimates to include non-federally managed species such as Atlantic menhaden, and including discard estimates for all species. The WG gave helpful suggestions on additional sources of discard information for the indicators.

The primary WG discussion was on how the EOF indicators might be used and how to design a simulation analysis that gives insight into practical management use. From the management perspective, if we are able to come up with well defined ecosystem overfishing reference points, how should managers use this information when not set up to specifically handle that in the current process? An analysis should give insight into the specific advice we should offer if we are exceeding a threshold. Conversely, if the indicator is in the good range what does that mean? What are the implications for the ecosystem? The Council has been asking for this, what are thresholds, where are we with respect to them, are we near a tipping point?

The WG suggested that maximizing social benefits may be a good way to measure outcomes. Reference points would not be used to optimize, but to identify states we don't want to go into. The goal of the EOF threshold would be to define "safe operating space" rather than pretending we can control the ecosystem by fishing it into an optimal state to meet our needs. The thresholds should define the bounds where fishing causes poor system performance (as defined using multiple Council objectives), but also ideally identify tradeoffs across species within the safe zone of fishing.

The WG agreed that to be used in the regional operational management context, more regional analysis of EOF thresholds and detail on regional productivity is important. A globally-derived EOF threshold is less useful when we have the ability to tailor this to our region. For example, some issues to address include how to deal with migratory species in the region vs resident species, and how to allocate each to the system primary production budget?

The WG will continue to design simulations and scenarios to define more clearly for the Council what is ecosystem overfishing, and identify what species can be backed off on to correct any overfishing. The simulation discussion could include--is it wise to reduce landings on one or two species vs equally across all? Where is the biggest bang for your buck to the ecosystem and which managers should do it? The WG recognized that this is more complex than MAFMC management, and begins discussion of how to move forward more broadly with other management partners. At upcoming meetings, the WG will review available ecosystem models (e.g. Northeast US Atlantis ) and generate scenarios that could be tested to address the questions raised in this discussion.

#### Index methods for ecosystem performance

John Walden (NEFSC) presented an overview of [Index numbers](https://drive.google.com/drive/folders/1GUbsGuVEHfavrddt6yXc8-Y6iS4qa0GM) which evaluate sets of environmental indicators and output indicators to determine system performance at the July meeting. The approach combines important ecosystem outputs (e.g. commercial revenue, recreational days fished, right whale abundance) and likely ecosystem drivers of change in these outputs (e.g., chlorophyl a, zooplankton, aggregate fish biomass) into an analysis evaluating aggregating inputs and outputs into single indicators used to determine whether system performance has improved over time relative to a benchmark. The analysis uses Data Envelopment Analysis (DEA) to identify a "best practice frontier" of maximum output given system input, and determine the how current performance relates to this frontier.

A initial case study using the SOE indicators identified above was presented, evaluating whether system performance changed after the passage of the Sustainable Fisheries Act (SFA). Both outputs and environmental conditions improved post-SFA, but the overall performance of the ecosystem did not. A second case study focused on Mid-Atlantic region indicators of commercial revenue and recreational days fished as outputs, and regional zooplankton and survey aggregate fish biomass as inputs. In this example, the recreational index was driving the overall declining trend in performance since 2010 even with the model predicting better/improved environmental conditions. John noted that an advantage of the Index numbers method is that the weights for the outputs and environmental factors used in the index do not need to be pre-determined; they are endogenously calculated as part of the DEA model.

The WG saw considerable promise in this method. It has the potential to create one or a few different system level index(es) which is something the Council has been looking for. The point of the presentation and work so far was to demonstrate the utility of the approach and not prescribe the specific inputs and outputs used -- certainly other inputs and outputs related to different priorities can be considered and included. The WG asked how many indices could potentially be included; this is limited by the number of observations. With limited data and many indicators included, the model can't explore the frontier space appropriately. The WG had some suggestions to increase observations and include more indices, including looking at data at a monthly or seasonal timesteps where possible. Another approach would be to evaluate drivers for specific objectives separately. We could Consider developing a model for commercial landings and one for recreational landings as opposed to a full ecosystem performance model. Finally, the WG asked whether there would be a need to lag the data within the input and output information? We would expect some of these dynamics to respond immediately to environmental drivers, and others might be delayed.

WG members Geret DePiper and Sarah Gaichas plan to meet with other SOE leads to explore how to bring Index Numbers forward in the upcoming SOE cycle.

### Objective 3:

Work under Objective 3 continues with the participation of several working group members in multiple Research Track assessment working groups:

-   Gavin Fay, black sea bass WG (ongoing)
-   Sarah Gaichas, bluefish WG (ongoing)
-   Paul Rago, *Illex* WG (complete)
